Set up a "Hello world" project as one app with Webpack #1
MarcoDDM/hello-rails_react pull request #2
Opened 2024-01-31 18:22 UTC by MarcoDDM

## Learning objectives
- Implement a connection between a Ruby on Rails back-end and React front-end.
- Understand the pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

### Project requirements

 - Create a new Rails app called 'hello-rails-react'.
      - Use the command `rails new -j webpack my_new_rails_app` as described in the previous lesson's tutorial.
 - Verify that the `jsbundling-rails` gem is added to your Gemfile.
 - Initialize your project with Git.
 - Install needed node dependencies as described in the previous lesson's tutorial.
 - Create a `babel.config.js` in the root folder of your project as described in the previous lesson's tutorial.
 - Update `webpack.config.js` to include the babel loader as described in the previous lesson's tutorial.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
 - Create a static view that will be the root of your app.

---------

- Create the `App` component with react-router and render it in your static view.
- Create the `Greeting` component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your `Greeting` component.

Thank you for your time! Do not hesitate to contact me if there are any changes needed.

2024-01-31 19:21 UTC, Olamarx requested changes
Hi @MarcoDDM,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme file, kindly review it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-31 20:23 UTC, Strangeal requested changes
Hi @MarcoDDM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjBkMDI3OWJlYzRhNWVlNmIyZmE5NjU5NzFlZTA0NDVjZWFhMmQ2NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Well structured project ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-31 20:23 UTC, Strangeal commented on webpack.config.js
> +  ...webpackConfig,
- [ ] Great job so far in your implementation. However, I would like to highlight that your app isn't running as expected and this is due to the fact there's a missing package in your `webpack.config.js`. In the attached, you will see the details of the error. To fix this I would recommend following the instructions in this blog post and using the `webpack.config.js` given in the tutorials.
<img width="1069" alt="Screenshot 2024-01-31 at 20 10 16" src="https://github.com/MarcoDDM/hello-rails_react/assets/107192076/203c5f12-833e-4515-b252-4425d49fa4d0">

2024-01-31 21:26 UTC, topeogunleye requested changes
Hi @MarcoDDM, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
1. **Issue Resolution**: The student effectively addressed the issue highlighted in the previous review regarding the missing package in the webpack configuration. 

2. **Implementation Improvement**: By following the recommended instructions from the blog post and using the suggested webpack configuration, the student successfully resolved the issue and improved the functionality of the application.

3. **Proactive Approach**: It's commendable that the student took proactive steps to rectify the issue and ensure that the application runs as expected.

4. **Adaptability**: Demonstrating adaptability by incorporating external resources and tutorials to enhance their implementation reflects a proactive and resourceful approach to problem-solving.

5. **Effective Communication**: The student effectively communicated their understanding of the issue and implemented the necessary changes, showcasing their responsiveness to feedback and commitment to improvement.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-31 21:26 UTC, topeogunleye commented on webpack.config.js
Hi, I tried to run your Rails and React application, but I encountered an error in the `ApiController#greetings` method. The error message was:

```
NoMethodError in ApiController#greetings
undefined method `content' for nil:NilClass
```

This means that you are calling the `content` method on a `nil` object, which does not exist. In this case, the `nil` object is the result of `Message.order('RANDOM()').first`, which means that there are no records in the `messages` table. You can check this by running `Message.count` in the Rails console.

To fix this error, you need to either make sure that there is at least one record in the `messages` table, or handle the case when there is none. For example, you can use the `try` method to avoid calling `content` on `nil`, or use a default value or a custom message if there is no message. You can find more details and examples on how to do this in my previous message.

Please let me know if you have any questions or need any help. I appreciate your effort and creativity in building this application. 😊.

Source: Conversation with Bing, 1/31/2024
(1) How to write code review comments | eng-practices. https://google.github.io/eng-practices/review/reviewer/comments.html.
(2) Best practices for writing code comments - Stack Overflow. https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/.
(3) How to Make Good Code Reviews Better - Stack Overflow. https://stackoverflow.blog/2019/09/30/how-to-make-good-code-reviews-better/.
(4) en.wikipedia.org. https://en.wikipedia.org/wiki/Comment_(computer_programming).

<img width="823" alt="image" src="https://github.com/MarcoDDM/hello-rails_react/assets/52934128/8d042d4e-abd5-4147-a39f-32f9a00acf90">

2024-02-01 23:31 UTC, Reem-lab approved these changes
# Hi @MarcoDDM,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Descriptive PR ⭐
- [ ]  Followed Gitflow ⭐
- [ ] Great job working on the API💪🏻
- [ ] Great job working on the requested changes🔥🔥



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-01 23:33 UTC, merged